name: Always Success Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  always-success:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Check
        run: python .github/scripts/check.py
